// Tests for the launcher's update check (D19).
//
// The check itself is one HTTPS GET, which is asserted by hand rather than here; what is tested
// is everything the answer turns into - the release manifest, the version comparison, and the two
// decisions the launcher makes (is there an update, and should the user be asked). Those are the
// rules a release can get wrong quietly, so they are decided from text rather than from a release
// that happens to exist.
//
// The third rule - "never ask twice about the same release" - is the profile's:
// launcher_profile_session_tests.cpp covers the record this module reads.

#include <string>
#include <string_view>

#include "check.h"
#include "update_check.h"

using namespace rb_blitz::launcher;
using rb_blitz::test::BeginCase;

namespace {

void CheckStrEq(const char* file, int line, std::string_view actual, std::string_view expected) {
  ++rb_blitz::test::g_checks;
  if (actual != expected) {
    rb_blitz::test::Fail(file, line, "expected \"" + std::string(expected) + "\", got \"" +
                                         std::string(actual) + "\"");
  }
}

void CheckContains(const char* file, int line, std::string_view haystack,
                   std::string_view needle) {
  ++rb_blitz::test::g_checks;
  if (haystack.find(needle) == std::string_view::npos) {
    rb_blitz::test::Fail(file, line, "expected to find \"" + std::string(needle) + "\" in \"" +
                                         std::string(haystack) + "\"");
  }
}

#define CHECK_STR_EQ(actual, expected) CheckStrEq(__FILE__, __LINE__, actual, expected)
#define CHECK_CONTAINS(haystack, needle) CheckContains(__FILE__, __LINE__, haystack, needle)

// A manifest in the shape installer/tools/embed_config.cpp writes it, with every key the
// launcher reads.
std::string ManifestText(std::string_view version, bool requires_game_data,
                         std::string_view payload_url) {
  return "# Generated by tools/embed_config.cpp from installer/config/pins.toml.\n"
         "# Do not edit; edit pins.toml and rebuild.\n"
         "schema_version = 1\n"
         "\n"
         "version = \"" + std::string(version) + "\"\n"
         "requires_game_data = " + (requires_game_data ? "true" : "false") + "\n"
         "payload_version = \"" + std::string(version) + "\"\n"
         "payload_url = \"" + std::string(payload_url) + "\"\n"
         "payload_sha256 = \"6524a193de32de2961cd95329b65cdeda8dec9d813cbdf9bbd8dd3646ca8d5ff\"\n"
         "payload_size = 10366787\n"
         "payload_commit = \"1e3ca35e0aa84176ddb244a6c590784cdfa59002\"\n";
}

constexpr const char* kPayloadUrl = "https://example.invalid/payload.zip";

// The state of a check that has finished: what the launcher's own thread publishes.
UpdateCheck Fetched(std::string_view version, bool requires_game_data,
                    std::string_view payload_url = kPayloadUrl) {
  UpdateCheck check;
  check.state = UpdateCheck::State::kDone;
  std::string error;
  const std::string text = ManifestText(version, requires_game_data, payload_url);
  if (ParseReleaseManifest(text, &check.manifest, &error)) {
    check.fetched = true;
  }
  return check;
}

UpdateCheck Unreadable() {
  UpdateCheck check;
  check.state = UpdateCheck::State::kDone;
  return check;
}

}  // namespace

int main() {
  BeginCase("the release manifest the installer generates is read");

  ReleaseManifest manifest;
  std::string error;
  CHECK_TRUE(ParseReleaseManifest(ManifestText("0.2.0", true, kPayloadUrl), &manifest, &error));
  CHECK_EQ(manifest.schema_version, kReleaseManifestSchemaVersion);
  CHECK_STR_EQ(manifest.version, "0.2.0");
  CHECK_TRUE(manifest.requires_game_data);
  CHECK_STR_EQ(manifest.payload_url, kPayloadUrl);

  // The keys the updater owns are ignored rather than refused: a release has to be able to add
  // one without this build going blind to the update.
  CHECK_TRUE(ParseReleaseManifest(
      "schema_version = 1\nversion = \"9.9.9\"\npayload_url = \"https://example.invalid/p.zip\"\n"
      "payload_updater_url = \"https://example.invalid/u.exe\"\nsomething_new = \"x\"\n",
      &manifest, &error));
  CHECK_STR_EQ(manifest.version, "9.9.9");
  // Absent means false: a manifest written before the flag existed describes a release that
  // keeps the game data.
  CHECK_FALSE(manifest.requires_game_data);

  BeginCase("a manifest this build cannot act on is refused");

  CHECK_FALSE(ParseReleaseManifest("version = \"1.0\"\n", &manifest, &error));
  CHECK_CONTAINS(error, "schema_version");
  CHECK_FALSE(ParseReleaseManifest("schema_version = 2\nversion = \"1.0\"\n", &manifest, &error));
  CHECK_CONTAINS(error, "schema_version");
  CHECK_FALSE(ParseReleaseManifest("schema_version = 1\n", &manifest, &error));
  CHECK_CONTAINS(error, "version");
  CHECK_FALSE(ParseReleaseManifest("schema_version = 1\nversion = \"\"\n", &manifest, &error));
  CHECK_FALSE(ParseReleaseManifest("schema_version = 1\nversion = 1.0\n", &manifest, &error));
  CHECK_CONTAINS(error, "not a string");
  CHECK_FALSE(ParseReleaseManifest("schema_version = 1\nnonsense\n", &manifest, &error));
  CHECK_FALSE(ParseReleaseManifest("schema_version = 1\nrequires_game_data = maybe\n", &manifest,
                                   &error));

  BeginCase("a second copy re-saved by an editor still reads");

  // A byte order mark is what an editor adds; the generator does not write one, and a mark read
  // as part of the first key would make the whole manifest unreadable.
  CHECK_TRUE(ParseReleaseManifest(
      ("\xEF\xBB\xBF" "schema_version = 1\nversion = \"3.0\"\n"
       "payload_url = \"https://example.invalid/p.zip\"\n"),
      &manifest, &error));
  CHECK_STR_EQ(manifest.version, "3.0");

  BeginCase("versions compare by their dotted numbers");

  CHECK_EQ(CompareVersions("1.0.0", "1.0.0"), 0);
  CHECK_EQ(CompareVersions("0.1.0", "0.2.0"), -1);
  CHECK_EQ(CompareVersions("0.2.0", "0.1.0"), 1);
  CHECK_EQ(CompareVersions("0.1.0", "0.1.1"), -1);
  CHECK_EQ(CompareVersions("1.0", "1.0.0"), 0);
  CHECK_EQ(CompareVersions("1.0.0", "1.0"), 0);
  CHECK_EQ(CompareVersions("0.10.0", "0.9.9"), 1);
  CHECK_EQ(CompareVersions("2.0", "10.0"), -1);
  CHECK_EQ(CompareVersions("", ""), 0);
  // A release tag that is not a dotted number never reads as *newer* than what is running: every
  // component this build cannot parse counts as zero (NextVersionPart), so an unreadable tag
  // ends in silence rather than in a prompt.
  CHECK_TRUE(CompareVersions("v1.0", "1.0") <= 0);
  CHECK_TRUE(CompareVersions("1.0-beta", "1.0") <= 0);

  BeginCase("an update is offered only when there is one to install");

  // Never asked - no release channel, or --no-update-check - is its own answer: the launcher
  // says it does not check rather than claiming to be up to date.
  UpdateReport report = EvaluateUpdate(UpdateCheck{}, "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kDisabled);
  CHECK_FALSE(report.ask);
  CHECK_CONTAINS(UpdateButtonText(report), "does not check");

  // Still checking: nothing is decided, and nothing is said.
  UpdateCheck checking;
  checking.state = UpdateCheck::State::kChecking;
  report = EvaluateUpdate(checking, "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kChecking);
  CHECK_FALSE(report.ask);

  // Fetched nothing - no network, no channel, a manifest this build cannot read.
  report = EvaluateUpdate(Unreadable(), "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kNoUpdate);
  CHECK_FALSE(report.ask);

  // The same release that is running, and an older one.
  report = EvaluateUpdate(Fetched("0.1.0", false), "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kNoUpdate);
  report = EvaluateUpdate(Fetched("0.0.9", false), "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kNoUpdate);

  // A newer release whose payload travels inside its setup executable: there is nothing an
  // updater could install, so the launcher says nothing rather than offering a dead end.
  report = EvaluateUpdate(Fetched("0.2.0", false, ""), "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kNoUpdate);
  CHECK_FALSE(report.ask);

  // A newer release with something to install: offered, and asked about once.
  report = EvaluateUpdate(Fetched("0.2.0", false), "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kAvailable);
  CHECK_STR_EQ(report.version, "0.2.0");
  CHECK_FALSE(report.requires_game_data);
  CHECK_TRUE(report.ask);

  report = EvaluateUpdate(Fetched("0.2.0", true), "0.1.0", "");
  CHECK_TRUE(report.status == UpdateStatus::kAvailable);
  CHECK_TRUE(report.requires_game_data);

  BeginCase("a declined release is not asked about twice, and a newer one is");

  // The user said no to this one: it stays available - the button is still there - and the
  // prompt never opens again.
  report = EvaluateUpdate(Fetched("0.2.0", false), "0.1.0", "0.2.0");
  CHECK_TRUE(report.status == UpdateStatus::kAvailable);
  CHECK_FALSE(report.ask);

  // A release newer than the declined one is a new question, which is the only case D19 allows
  // a second prompt. A release older than the declined one is not asked about either: a profile
  // that remembers a later answer has already seen this one.
  report = EvaluateUpdate(Fetched("0.3.0", false), "0.1.0", "0.2.0");
  CHECK_TRUE(report.status == UpdateStatus::kAvailable);
  CHECK_TRUE(report.ask);
  report = EvaluateUpdate(Fetched("0.2.0", false), "0.1.0", "0.3.0");
  CHECK_FALSE(report.ask);

  BeginCase("the bar's Update option says which state it is in");

  // The button is drawn either way, so what it says is the whole of what changes.
  report = EvaluateUpdate(checking, "0.1.0", "");
  CHECK_CONTAINS(UpdateButtonText(report), "Checking");
  report = EvaluateUpdate(Unreadable(), "0.1.0", "");
  CHECK_CONTAINS(UpdateButtonText(report), "newest release");
  report = EvaluateUpdate(Fetched("0.2.0", false), "0.1.0", "");
  CHECK_CONTAINS(UpdateButtonText(report), "0.2.0");

  BeginCase("the prompt says which release, and what accepting it means");

  report = EvaluateUpdate(Fetched("0.2.0", false), "0.1.0", "");
  CHECK_CONTAINS(UpdatePromptText(report), "0.2.0");
  CHECK_CONTAINS(UpdatePromptText(report), "are kept");
  report = EvaluateUpdate(Fetched("0.2.0", true), "0.1.0", "");
  CHECK_CONTAINS(UpdatePromptText(report), "0.2.0");
  CHECK_CONTAINS(UpdatePromptText(report), "game files");

  return rb_blitz::test::Finish();
}
